# HHPNet/core container to run composer
FROM composer/composer:alpine
MAINTAINER Javi M <me@javi.yt>

RUN apk update

RUN apk add autoconf openssl-dev g++ make

RUN pecl install mongodb && \
    docker-php-ext-enable mongodb

RUN apk del --purge autoconf openssl-dev g++ make